config/routes.rb
Rails.application.routes.draw do
  
  get 'likes/create'
  get 'likes/destroy'
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :ideas do
  # Routes written inside of a block passed
  # to a 'resources' method will be pre-fixed
  # by a path corresponding to the passed in symbol.
  # In this case all nested routes will be
  # prefixed with '/questions/:question_id/'
  resources :reviews, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end
  get('/', { to: 'ideas#index', as: 'root' })

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new
    alias_action :create, :read, :update, :destroy, :delete, to: :crud

    can(:crud, Idea) do |idea|
      idea.user == user
    end

    can :crud, Review do |rev|
      rev.user == user || rev.idea.user == user
    end

    can :like, Idea do |idea|
      user.persisted? && idea.user != user
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user

    has_many :reviews, dependent: :destroy

    validates(:title, presence: true, uniqueness: true)

    validates(
      :description,  presence: { message: "must exist" },
              length: { minimum: 5 }
    )
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :idea_id, uniqueness: { scope: :user_id }
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :idea
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas, dependent: :nullify
  has_many :reviews, dependent: :nullify
  
  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea 

  has_secure_password

  validates(:email, presence: true, uniqueness: true, format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
  
    def current_user
      if session[:user_id].present?
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
    helper_method :current_user
  
    def user_signed_in?
      current_user.present?
    end
    helper_method :user_signed_in?
  
    def authenticate_user!
      unless user_signed_in?
        flash[:danger] = "You must sign in or sign up first!"
        redirect_to new_session_path
      end
    end
  end
  

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]


  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to idea_path(@idea.id)
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @reviews = @idea.reviews.order(created_at: :desc)
    @like = @idea.likes.find_by(user: current_user)
  end
  
  def index
    @ideas = Idea.all.order(created_at: :desc)
  
  end

  def destroy
    @idea.destroy
    redirect_to root_path
  end

  def edit
  end

  def update
    if @idea.update idea_params
      redirect_to idea_path(@idea.id)
    else
      render :edit
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def find_idea
    @idea = Idea.find(params[:id])
  end

  def authorize
    redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @idea)
    end 
  end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  
  def create
    idea = Idea.find params[:idea_id]
    like = Like.new(user: current_user, idea: idea)
  
    if not can?(:like, idea)
      flash[:danger] = "That's a bit narcissistic..."
      return redirect_to idea_path(idea)
    end
    if like.save
      flash[:success] = "Idea Liked!"
    else
      flash[:danger] = "Already Liked..."
    end

    redirect_to idea_path(idea)
  end

  def destroy
    idea = Idea.find params[:idea_id]
    @like = Like.find params[:id]
    @like.destroy

    flash[:success] = "Idea Unliked!"
    redirect_to idea_path(idea)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_review, only: [:show, :edit, :update, :destroy]
    before_action :authorize!, only: [:edit, :destroy, :update]

    def create
        @idea = Idea.find(params[:idea_id])
        @review = Review.new review_params
        @review.idea = @idea
        @review.user = current_user
        if @review.save
            redirect_to idea_path(@idea)
        else
            @reviews = @idea.reviews.order(created_at: :desc)
            render 'ideas/show'
        end
    end

    def destroy
        @review = Review.find(params[:id])
        if can?(:crud, @review)
            @review.destroy
            redirect_to idea_path(@review.idea)
          else
            head :unauthorized
          end
    end

    private
    
      def review_params
        params.require(:review).permit(:body)
      end

      def find_review
        @review = Review.find(params[:id])
      end

    def authorize!
        redirect_to root_path, alert: "access denied" unless can? :crud, @review
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user&.authenticate params[:password]
        session[:user_id] = user.id
        redirect_to root_path, notice: 'Logged in'
      else
        flash[:alert] = "Wrong email or password"
        render :new
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
       render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/edit.html.erb
<%= form_with(model: [@idea], local: true) do |f| %>



    <% if @idea.errors.present? %>
        <p class="form-errors">
        <%= @idea.errors.full_messages.join(", ") %>  
      </p>
    <% end %>
      <%= f.label :title %>
    <div class="form-group">

        <%= f.text_field(
        :title, cols: 50,
        class: "form-control"
        ) %>
    </div>
    
      <%= f.label :description %>
    <div class="form-group">

        <%= f.text_area(
        :description, cols: 50, rows: 5,
        class: "form-control"
        ) %>
    </div>
        <%= f.submit "Submit", class: "btn btn-outline-primary" %>
  <% end %>

app/views/ideas/index.html.erb
<div class="cards">
  <% @ideas.each do |idea| %>
    <div class="card">
    <div class="card-body">
        
        <%= link_to(idea.title, idea_path(idea)) %> <br />
        <small>
            Posted by <%= idea.user.name %> <%= time_ago_in_words(idea.created_at)  %> ago
        </small>
      <div>
  <% if @like.present? %>
  <p><%= idea.likes.count %></p>
    <%=
      link_to(
        "liked",
        idea_likes_path(@idea, @like),
        method: :delete
      )
    %>
  <% else %>
    <%=
      link_to(
        "Like",
        idea_likes_path(idea),
        method: :post
      )
    %>

  <% end %>

  <span><%= pluralize(idea.likes.count, "like") %></span>
</div>
    </div>
    </div>
  <% end %>
</div>

app/views/ideas/new.html.erb
<%= form_with(model: [@idea], local: true) do |f| %>



    <% if @idea.errors.present? %>
        <p class="form-errors">
        <%= @idea.errors.full_messages.join(", ") %>  
      </p>
    <% end %>
      <%= f.label :title %>
    <div class="form-group">

        <%= f.text_field(
        :title, cols: 50,
        class: "form-control"
        ) %>
    </div>
    
      <%= f.label :description %>
    <div class="form-group">

        <%= f.text_area(
        :description, cols: 50, rows: 5,
        class: "form-control"
        ) %>
    </div>
        <%= f.submit "Submit", class: "btn btn-outline-primary" %>
  <% end %>

app/views/ideas/show.html.erb
<h3><%= @idea.title %></h3>

<p><%= @idea.description %></p>

<div>
  <small>
    Posted <%= time_ago_in_words(@idea.created_at)  %> ago by <%= @idea.user.name %>
  </small>
</div>

<div>
  <% if can?(:crud, @idea) %>
    <small>
        <%= link_to "Edit", edit_idea_path(@idea), class: "btn btn-outline-primary" %>

    </small> 
    
    <small>
        <%= link_to(
        "Delete", idea_path(@idea), class: "btn btn-outline-primary",
        method: :delete,
        data: { confirm: "Are you sure?"}) %>
  <% end %>

    </small>
</div>

</br>

<div>
  <% if @like.present? %>
    <%=
      link_to(
        "Liked",
        idea_like_path(@idea, @like),
        method: :delete
      )
    %>
  <% else %>
    <%=
      link_to(
        "Like",
        idea_likes_path(@idea),
        method: :post
      )
    %>
  <% end %>

  <span><%= pluralize(@idea.likes.count, "like") %></span>
</div>

</br>

<section>
  <h3>Reviews</h3>

  <%= form_with(model: [@idea, @review], local: true) do |f| %>
    <% if @review.errors.present? %>
      <p class="form-errors">
        <%= @review.errors.full_messages.join(", ") %>
      </p>
    <% end %>


    <div class="form-group">
        <%= f.text_area(
      :body, cols: 50, rows: 5,
      placeholder: "What are your thoughts about this idea?",
      class: "form-control"
      ) %>
    </div>
    <%= f.submit "Submit Review", class: "btn btn-outline-primary" %>
  <% end %>
</section>

  </br>
  
<section>
  <% @reviews.each do |review| %>
    <p>
      <%= review.body %> <br />
      Posted by <%= review.user.name %>
      <div>
          <% if can?(:crud, review) %>
        <small>
          <%= link_to(
          "Delete",
          idea_review_path(@idea, review),
          method: :delete, data: {
            confirm: "Are you sure?"
          }
          ) %>
          </small>
        <% end %>
      </div>
    </p>
  <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar bg-light">

    <span class="navbar-text">
  <img src="https://cdn0.iconfinder.com/data/icons/colourful-education/250/bulb-512.png" class="nav-image">
       
    <%= link_to 'Home', root_path %>
    |
    <%= link_to 'New Idea', new_idea_path %>
    |
    <%= link_to 'All Ideas', ideas_path %>
    </span>

    <span class="navbar-text">
    <% if user_signed_in? %>
      Hello <%= current_user.name %> |
      <%= link_to "Logout", session_path, method: :delete, data: {confirm: "are you sure you want to log out?"} %>
    <% else %>
      <%= link_to "Login", new_session_path %>
      |
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <% flash.each do |type, message| %>
      <div class="flash flash-<%= type %>">
        <%= message %>
      </div>
      </span>
    <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_with model: @user, local: true do |f| %>
  <% if @user.errors.any? %>
<p>
<%= @user.errors.full_messages.join (", ") %>
</p>
<% end %>
<div>
<%= f.label :name%>
<%= f.text_field :name%>
</div>
<div>
<%= f.label :email%>
<%= f.email_field :email%>
</div>
<div>
<%= f.label :password%>
<%= f.password_field :password%>
</div>
<div>
<%= f.label :password_confirmation%>
<%= f.password_field :password_confirmation%>
</div>
  <%= f.submit "Sign Up" %>
<% end %>